project_id = "xtmcrrwxthlzknufbbdw"

[functions.process-order]
verify_jwt = true

[functions.process-payment-request]
verify_jwt = true

[functions.send-telegram-notification]
verify_jwt = true

[functions.notify-admin-new-order]
verify_jwt = false

[functions.notify-admin-new-payment]
verify_jwt = false